image: androidsdk/android-30

before_script:
  # Ask gradle to put everything to .gradle dir so that we can cache it
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  key: "mealie-android"
  paths:
    - .gradle

stages:
  - build
  - test

assembleDebug:
  interruptible: true
  stage: build
  needs: [ ]
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/

debugTests:
  interruptible: true
  stage: test
  needs: [ "assembleDebug" ]
  script:
    - ./gradlew testDebug
  artifacts:
    when: always
    reports:
      junit: ./**/build/test-results/**/TEST-*.xml