[versions]
# https://maven.google.com/web/index.html?q=com.android.tools.build#com.android.tools.build:gradle
androidGradlePlugin = "7.2.1"
# https://developers.google.com/android/guides/google-services-plugin
googleServicesPlugin = "4.3.13"
# https://mvnrepository.com/artifact/com.google.firebase/firebase-crashlytics-gradle
firebaseCrashlytics = "2.9.1"
# https://kotlinlang.org/docs/gradle.html
kotlin = "1.7.10"
# https://developer.android.com/jetpack/androidx/releases/navigation
googleNavigation = "2.5.1"
# https://dagger.dev/hilt/gradle-setup
hilt = "2.43.1"

[libraries]
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
google-servicesPlugin = { group = "com.google.gms", name = "google-services", version.ref = "googleServicesPlugin" }
firebase-crashlyticsPlugin = { group = "com.google.firebase", name = "firebase-crashlytics-gradle", version.ref = "firebaseCrashlytics" }
jetbrains-kotlinPlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
jetbrains-serializationPlugin = { group = "org.jetbrains.kotlin", name = "kotlin-serialization", version.ref = "kotlin" }
navigation-safeArgsPlugin = { group = "androidx.navigation", name = "navigation-safe-args-gradle-plugin", version.ref = "googleNavigation" }
dagger-hiltPlugin = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "hilt" }
