name: Sign

on:
  push:
    branches:
      - master

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Sign APK
        env:
          MEALIENT_KEY_STORE: ${{ secrets.MEALIENT_KEY_STORE }}
          MEALIENT_KEY_STORE_PASSWORD: ${{ secrets.MEALIENT_KEY_STORE_PASSWORD }}
          MEALIENT_KEY_ALIAS: ${{ secrets.MEALIENT_KEY_ALIAS }}
          MEALIENT_KEY_PASSWORD: ${{ secrets.MEALIENT_KEY_PASSWORD }}
        run: |
          echo "$MEALIENT_KEY_STORE" | base64 -d -o app/keystore.jks
          echo "storeFile=keystore.jks" > keystore.properties
          echo "storePassword=$MEALIENT_KEY_STORE_PASSWORD" >> keystore.properties
          echo "keyAlias=$MEALIENT_KEY_ALIAS" >> keystore.properties
          echo "keyPassword=$MEALIENT_KEY_PASSWORD" >> keystore.properties
          ./gradlew assembleRelease --no-daemon

      - name: Upload signed APK
        uses: actions/upload-artifact@v2
        with:
          name: Signed APK
          path: app/build/outputs/apk/release/*.apk