name: Sign

on:
  push:
    branches:
      - master

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Sign APK
        env:
          MEALIENT_KEY_STORE: ${{ secrets.MEALIENT_KEY_STORE }}
          MEALIENT_KEY_STORE_PASSWORD: ${{ secrets.MEALIENT_KEY_STORE_PASSWORD }}
          MEALIENT_KEY_ALIAS: ${{ secrets.MEALIENT_KEY_ALIAS }}
          MEALIENT_KEY_PASSWORD: ${{ secrets.MEALIENT_KEY_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          APPSWEEP_API_KEY: ${{ secrets.APPSWEEP_API_KEY }}
        run: |
          echo "$MEALIENT_KEY_STORE" | base64 -d > app/keystore.jks
          echo "storeFile=keystore.jks" > keystore.properties
          echo "storePassword=$MEALIENT_KEY_STORE_PASSWORD" >> keystore.properties
          echo "keyAlias=$MEALIENT_KEY_ALIAS" >> keystore.properties
          echo "keyPassword=$MEALIENT_KEY_PASSWORD" >> keystore.properties
          ./gradlew build sonarqube uploadToAppSweepRelease --no-daemon
          cp app/build/outputs/apk/release/*.apk mealient-release.apk

      - name: Upload signed APK
        uses: actions/upload-artifact@v2
        with:
          name: Signed APK
          path: mealient-release.apk